import OpenAI from "openai";
import { getOpenAIConfig } from "@/lib/env/openai";
import { destinationBriefBodySchema, type DestinationBriefBody } from "./briefSchema";
import { attachMarkdownOutput, normalizeBriefInput } from "./generateDestinationBrief";
import type { DestinationBrief, DestinationBriefInput } from "./types";

const SYSTEM_PROMPT = `You are an expert SEO and destination marketing strategist for DMO (Destination Marketing Organization) content briefs.

You will receive:
1) Raw user form input for a content brief
2) A baseline brief JSON generated by deterministic templates

Your job is to ENHANCE the baseline brief: improve clarity, strategic wording, title tags, meta descriptions, H1 options, search intent explanation, FAQ phrasing, and editorial guidance.

CRITICAL RULES (violations are unacceptable):
- Do NOT generate final article copy. Output is a planning brief only.
- Do NOT invent local businesses, attractions, events, dates, prices, hours, distances, or neighborhoods.
- If the user provided NO local details, localKnowledgeNeeded.detailsProvided MUST remain an empty array.
- Only include local places/facts in detailsProvided if they appear verbatim in the user's localDetailsProvided field.
- Do not add new URLs to internal links; only use links/categories from the baseline or user input.
- Keep the same JSON structure. Return valid JSON only. No markdown fences or commentary.
- Do not use em dashes (—). Use periods, commas, or colons instead.
- Preserve factual overview fields (destination, contentType, primaryKeyword, audience, seasonality, businessGoal) from the baseline unless improving ctaGoal wording only.
- Keep recommendedStructure section count and levels similar to the baseline; you may refine heading wording but not invent specific venue names.`;

function buildUserPrompt(input: DestinationBriefInput, baseline: DestinationBrief): string {
  return JSON.stringify(
    {
      formInput: input,
      baselineBrief: {
        overview: baseline.overview,
        strategicObjective: baseline.strategicObjective,
        searchIntent: baseline.searchIntent,
        h1Options: baseline.h1Options,
        titleTagOptions: baseline.titleTagOptions,
        metaDescriptionOptions: baseline.metaDescriptionOptions,
        recommendedStructure: baseline.recommendedStructure,
        secondaryQueryMapping: baseline.secondaryQueryMapping,
        localKnowledgeNeeded: baseline.localKnowledgeNeeded,
        internalLinkRecommendations: baseline.internalLinkRecommendations,
        schemaRecommendations: baseline.schemaRecommendations,
        faqSuggestions: baseline.faqSuggestions,
        aiSearchReadinessNotes: baseline.aiSearchReadinessNotes,
        editorialGuidelines: baseline.editorialGuidelines,
        risksAndWatchouts: baseline.risksAndWatchouts,
        finalWriterChecklist: baseline.finalWriterChecklist,
      },
    },
    null,
    2,
  );
}

/**
 * Locks overview facts and local details so the model cannot hallucinate places.
 */
function sanitizeEnhancedBrief(
  enhanced: DestinationBriefBody,
  baseline: DestinationBrief,
  input: DestinationBriefInput,
): DestinationBriefBody {
  const userLocalDetails = normalizeBriefInput(input).localDetails;
  return {
    ...enhanced,
    overview: {
      ...baseline.overview,
      ctaGoal: enhanced.overview.ctaGoal || baseline.overview.ctaGoal,
    },
    localKnowledgeNeeded: {
      detailsProvided: userLocalDetails,
      additionalToConfirm:
        enhanced.localKnowledgeNeeded.additionalToConfirm.length > 0
          ? enhanced.localKnowledgeNeeded.additionalToConfirm
          : baseline.localKnowledgeNeeded.additionalToConfirm,
    },
  };
}

/**
 * Calls OpenAI to enhance a baseline brief. Returns null if unconfigured or on failure.
 */
export async function enhanceBriefWithOpenAI(
  input: DestinationBriefInput,
  baseline: DestinationBrief,
): Promise<DestinationBrief | null> {
  const { apiKey, model, isConfigured } = getOpenAIConfig();
  if (!isConfigured || !apiKey) return null;

  const client = new OpenAI({ apiKey });

  try {
    const completion = await client.chat.completions.create({
      model,
      temperature: 0.4,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        {
          role: "user",
          content: `Enhance this DMO content brief. Return a single JSON object matching the baseline structure.\n\n${buildUserPrompt(input, baseline)}`,
        },
      ],
    });

    const raw = completion.choices[0]?.message?.content;
    if (!raw) return null;

    const parsed: unknown = JSON.parse(raw);
    const validated = destinationBriefBodySchema.safeParse(parsed);
    if (!validated.success) {
      console.error("[OpenAI brief] Schema validation failed:", validated.error.flatten());
      return null;
    }

    const sanitized = sanitizeEnhancedBrief(validated.data, baseline, input);
    return attachMarkdownOutput(sanitized, input);
  } catch (error) {
    console.error("[OpenAI brief] Enhancement failed:", error);
    return null;
  }
}
