import OpenAI from "openai";
import { getOpenAIConfig } from "@/lib/env/openai";
import { destinationBriefBodySchema } from "./briefSchema";
import { attachMarkdownOutput, normalizeBriefInput } from "./generateDestinationBrief";
import { mergeOpenAIResponseWithBaseline, parseOpenAIJsonContent } from "./mergeOpenAIBrief";
import type { DestinationBrief, DestinationBriefInput } from "./types";
import type { DestinationBriefBody } from "./briefSchema";

const SYSTEM_PROMPT = `You are an expert SEO and destination marketing strategist for DMO (Destination Marketing Organization) content briefs.

You will receive:
1) Raw user form input for a content brief
2) A baseline brief JSON generated by deterministic templates

Your job is to ENHANCE the baseline brief: improve clarity, strategic wording, title tags, meta descriptions, H1 options, search intent explanation, FAQ phrasing, competitive notes, Simpleview platform notes, and editorial guidance.

Return ONE JSON object with EXACTLY these top-level keys (all required):
overview, strategicObjective, competitiveAndRefreshNotes, simpleviewPlatformNotes, searchIntent, h1Options, titleTagOptions, metaDescriptionOptions, recommendedStructure, secondaryQueryMapping, localKnowledgeNeeded, internalLinkRecommendations, schemaRecommendations, faqSuggestions, aiSearchReadinessNotes, editorialGuidelines, risksAndWatchouts, finalWriterChecklist

Enum rules (use exact strings only):
- searchIntent.primaryIntent and searchIntent.supportingIntents: "Inspiration", "Trip planning", "Transactional / booking support", "Local discovery", "Event planning", "Meeting planning", "Comparison / research"
- recommendedStructure[].level: "H1", "H2", or "H3"
- internalLinkRecommendations[].source: "provided" or "suggested-category"
- schemaRecommendations[].type: "Article", "FAQPage", "BreadcrumbList", "Event", "TouristDestination", "LocalBusiness", "ItemList", "HowTo", "CollectionPage"

CRITICAL RULES:
- Do NOT generate final article copy. Output is a planning brief only.
- Do NOT invent local businesses, attractions, events, dates, prices, hours, distances, or neighborhoods.
- If the user provided NO local details, localKnowledgeNeeded.detailsProvided MUST be [].
- Do not add new internal link URLs; only use links from the baseline or user input.
- Return valid JSON only. No markdown fences or commentary.
- Do not use em dashes.
- Preserve overview.destination, contentType, primaryKeyword, audience, seasonality, businessGoal from baseline (ctaGoal may be improved).
- Keep recommendedStructure section count and levels similar to the baseline.`;

export type EnhanceBriefResult =
  | { success: true; brief: DestinationBrief; usedLenientMerge?: boolean }
  | { success: false; error: string };

function buildUserPrompt(input: DestinationBriefInput, baseline: DestinationBrief): string {
  const { markdownOutput: _md, ...baselineBody } = baseline;
  return JSON.stringify({ formInput: input, baselineBrief: baselineBody }, null, 2);
}

function sanitizeEnhancedBrief(
  enhanced: DestinationBriefBody,
  baseline: DestinationBrief,
  input: DestinationBriefInput,
): DestinationBriefBody {
  const userLocalDetails = normalizeBriefInput(input).localDetails;
  return {
    ...enhanced,
    overview: {
      ...baseline.overview,
      ctaGoal: enhanced.overview.ctaGoal || baseline.overview.ctaGoal,
    },
    competitiveAndRefreshNotes:
      enhanced.competitiveAndRefreshNotes.length > 0
        ? enhanced.competitiveAndRefreshNotes
        : baseline.competitiveAndRefreshNotes,
    localKnowledgeNeeded: {
      detailsProvided: userLocalDetails,
      additionalToConfirm:
        enhanced.localKnowledgeNeeded.additionalToConfirm.length > 0
          ? enhanced.localKnowledgeNeeded.additionalToConfirm
          : baseline.localKnowledgeNeeded.additionalToConfirm,
    },
  };
}

function formatOpenAIError(error: unknown): string {
  if (error instanceof OpenAI.APIError) {
    return error.message;
  }
  if (error instanceof Error) {
    return error.message;
  }
  return "OpenAI request failed.";
}

/**
 * Calls OpenAI to enhance a baseline brief.
 */
export async function enhanceBriefWithOpenAI(
  input: DestinationBriefInput,
  baseline: DestinationBrief,
): Promise<EnhanceBriefResult> {
  const { apiKey, model, isConfigured } = getOpenAIConfig();
  if (!isConfigured || !apiKey) {
    return { success: false, error: "OPENAI_API_KEY is not configured." };
  }

  const client = new OpenAI({ apiKey });

  try {
    const completion = await client.chat.completions.create({
      model,
      temperature: 0.35,
      max_tokens: 12000,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        {
          role: "user",
          content: `Enhance this DMO content brief. Return the full JSON object with every required key.\n\n${buildUserPrompt(input, baseline)}`,
        },
      ],
    });

    const raw = completion.choices[0]?.message?.content;
    if (!raw) {
      return { success: false, error: "OpenAI returned an empty response." };
    }

    let parsed: unknown;
    try {
      parsed = parseOpenAIJsonContent(raw);
    } catch {
      return { success: false, error: "OpenAI returned invalid JSON." };
    }

    const strict = destinationBriefBodySchema.safeParse(parsed);
    let body: DestinationBriefBody;
    let usedLenientMerge = false;

    if (strict.success) {
      body = strict.data;
    } else {
      console.warn("[OpenAI brief] Strict validation failed, merging with baseline:", strict.error.flatten());
      body = mergeOpenAIResponseWithBaseline(parsed, baseline, input);
      usedLenientMerge = true;
    }

    const sanitized = sanitizeEnhancedBrief(body, baseline, input);
    return {
      success: true,
      brief: attachMarkdownOutput(sanitized, input),
      usedLenientMerge,
    };
  } catch (error) {
    console.error("[OpenAI brief] Enhancement failed:", error);
    return { success: false, error: formatOpenAIError(error) };
  }
}
